version: "3"
services:
    web:
        image: webserver
        ports:
          - "8090:80"
 
        volumes:
          - ./site_content/:/usr/share/nginx/html
        expose:
          - "8090"
        tty: true        
        stdin_open: true